import React, { useState } from 'react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { Copy, Check } from 'lucide-react'; // Optional icons

const PolyglotCodeCard = ({ title, snippets }) => {
  // Default to Java, but track which tab is active
  const [activeLang, setActiveLang] = useState('java');
  const [copied, setCopied] = useState(false);
  console.log("snippet", snippets)
  // Safety check: if no snippets, don't crash
  if (!snippets) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(snippets[activeLang]);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Tab definitions for cleaner rendering
  const tabs = [
    { id: 'java', label: '☕ Java' },
    { id: 'python', label: '🐍 Python' },
    { id: 'go', label: '🐹 Go' },
  ];

  return (
    <div className="w-full max-w-2xl mt-4 rounded-lg overflow-hidden border border-gray-700 bg-[#1e1e1e] shadow-xl">
      
      {/* --- HEADER & TABS --- */}
      <div className="flex items-center justify-between bg-[#252526] px-2 py-1 border-b border-gray-700">
        
        {/* Tab Buttons */}
        <div className="flex gap-1">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveLang(tab.id)}
              className={`px-4 py-2 text-sm font-medium transition-colors rounded-t-md ${
                activeLang === tab.id
                  ? 'bg-[#1e1e1e] text-white border-t-2 border-blue-500' // Active State
                  : 'text-gray-400 hover:bg-[#2d2d2d] hover:text-gray-200' // Inactive State
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Copy Button */}
        <button
          onClick={handleCopy}
          className="mr-2 p-1.5 text-gray-400 hover:text-white hover:bg-gray-700 rounded-md transition-all"
          title="Copy Code"
        >
          {copied ? <Check size={16} className="text-green-400" /> : <Copy size={16} />}
        </button>
      </div>

      {/* --- CODE DISPLAY AREA --- */}
      <div className="relative">
        <SyntaxHighlighter
          language={activeLang}
          style={vscDarkPlus} // VS Code Dark Theme
          customStyle={{
            margin: 0,
            padding: '1.5rem',
            fontSize: '0.9rem',
            lineHeight: '1.5',
            backgroundColor: '#1e1e1e', // Seamless match with container
          }}
          showLineNumbers={true}
          wrapLines={true}
        >
          {snippets[activeLang] || "// Code generation pending..."}
        </SyntaxHighlighter>
        
        {/* Floating Language Badge (Optional Aesthetic) */}
        <div className="absolute bottom-2 right-2 text-xs text-gray-500 opacity-50 select-none">
          Generated by Gemini 3 • {activeLang.toUpperCase()}
        </div>
      </div>
    </div>
  );
};

export default PolyglotCodeCard;